name: 'Extract Commit Action'
description:
  'Extracts information from commit messages. Defaults output variable name to
  "ENVIRONMENT" if not specified.'
author: 'somaz94'
inputs:
  commit_limit:
    description: 'Number of commits to retrieve.'
    required: true
  pretty:
    description: 'Whether to use pretty format for git log.'
    required: false
    default: 'false'
  key_variable:
    description:
      'The name of the key variable to set, defaults to "ENVIRONMENT".'
    required: false
    default: 'ENVIRONMENT'
  extract_command:
    description:
      'The command to use for extracting information from commit messages.'
    required: false
  branch:
    description: 'Specific branch to extract commits from'
    required: false
    default: 'main'
  skip_errors:
    description: 'Continue execution even if non-critical errors occur'
    required: false
    default: 'false'
  output_format:
    description: 'Format of the output (json/text)'
    required: false
    default: 'text'
outputs:
  key_variable:
    description: 'Extracted output key variable information.'
  value_variable:
    description: 'Extracted output value variable information.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    INPUT_COMMIT_LIMIT: ${{ inputs.commit_limit }}
    INPUT_PRETTY: ${{ inputs.pretty }}
    INPUT_KEY_VARIABLE: ${{ inputs.key_variable }}
    INPUT_EXTRACT_COMMAND: ${{ inputs.extract_command }}
    INPUT_BRANCH: ${{ inputs.branch }}
    INPUT_SKIP_ERRORS: ${{ inputs.skip_errors }}
    INPUT_OUTPUT_FORMAT: ${{ inputs.output_format }}
branding:
  icon: 'check-circle'
  color: 'yellow'
