name: 'Extract Commit Action'
description: 'Extracts information from commit messages. Defaults output variable name to "ENVIRONMENT" if not specified.'
inputs:
  commit_limit:
    description: 'Number of commits to retrieve.'
    required: true
  pretty:
    description: 'Whether to use pretty format for git log.'
    required: false
    default: 'false'
  output_variable:
    description: 'The name of the output variable to set, defaults to "ENVIRONMENT".'
    required: false
    default: 'ENVIRONMENT'
outputs:
  ENVIRONMENT:
    description: 'Extracted environment information.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    INPUT_COMMIT_LIMIT: ${{ inputs.commit_limit }}
    INPUT_EXTRACT_COMMAND: ${{ inputs.extract_command }}
    INPUT_PRETTY: ${{ inputs.pretty }}
    INPUT_OUTPUT_VARIABLE: ${{ inputs.output_variable }}
