name: Generator Contributors
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Generate changelog"]
    types:
      - completed

permissions:
  contents: write

jobs:
  update_contributors:
    name: Update Contributors
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0

      - name: Pull latest changes
        run: git pull origin main

      - name: Get contributors
        run: |
          {
            echo "# Contributors"
            echo ""
            echo "Contributions are welcome! Please feel free to submit a Pull Request."
            echo ""
            echo "## Contributors List"
            echo ""
            echo "Thanks goes to these wonderful people:"
            echo ""
            curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                 -H "Accept: application/vnd.github.v3+json" \
                 "https://api.github.com/repos/${{ github.repository }}/contributors" | \
            jq -r '.[] | select(.type != "Bot" and .login != "github-actions[bot]" and .login != "actions-user" and .login != "somaz94") | "- [@\(.login)](\(.html_url))"' | \
            sort
          } > CONTRIBUTORS.md

      - name: Commit changes
        uses: somaz94/go-git-commit-action@v1
        with:
          user_email: actions@github.com
          user_name: GitHub Actions
          commit_message: "docs: update CONTRIBUTORS.md"
          branch: main
          file_pattern: "CONTRIBUTORS.md"
          github_token: ${{ secrets.PAT_TOKEN }}
