name: Test Github Action Module

on:
  workflow_dispatch:
    inputs:
      run:
        description: "workflow run`"
        required: true
        default: "true"

jobs:

  acton-module:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 10
    
      - name: Extract Commit Information
        uses: somaz94/commit-info-extractor@v1
        with:
          commit_limit: 10
          extract_command: "grep -oP '\\bfix\\b'" # Use regex for values
          pretty: true
          output_variable: 'CUSTOM_ENV' # Key
