name: Example Workflow using Extract Commit Action

on:
  workflow_dispatch:
    inputs:
      run:
        description: 'workflow run'
        required: true
        default: 'true'
  workflow_run:
    workflows: ["Create release"]  # release.yml의 name과 일치해야 함
    types:
      - completed

permissions:
  contents: read

jobs:
  acton-module:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - name: Extract Commit Information (Basic)
        uses: somaz94/commit-info-extractor@v1
        id: extract_commit
        with:
          commit_limit: 10
          extract_command: "grep -oP '\\bfix\\b'" # Use regex for values
          pretty: true
          key_variable: 'CUSTOM_ENV' # Key

      - name: Print Output
        run: |
          echo "Extracted variable: ${{ steps.extract_commit.outputs.key_variable }} = ${{ steps.extract_commit.outputs.value_variable }}"

      - name: Extract Commit Information (With fail_on_empty)
        id: extract_commit_fail
        uses: somaz94/commit-info-extractor@v1
        continue-on-error: true
        with:
          commit_limit: 10
          extract_command: grep -oP \\bnonexistentword\\b
          pretty: true
          key_variable: environment
          fail_on_empty: true

      - name: Print Fail Test Output
        run: |
          echo "Fail test status: ${{ steps.extract_commit_fail.outcome }}"
